person:
  name: "Florian Glatz"
  jobTitle: "Blockchain Lawyer"
  description: "Working at the intersection of law, blockchain technology, and software development since 2014"
  url: "https://blockchain.lawyer"
  social:
    - "https://twitter.com/heckerhut"
    - "https://github.com/flotob"
    - "https://app.cg/u/~hz8ud4jRpdMYcpoWTSMmmz/"
  expertise:
    - "Blockchain Law"
    - "Legal Tech"
    - "Smart Contracts"
    - "Cryptocurrency Regulation"
    - "Web3"
    - "Decentralized Governance"
  organizations:
    - name: "Common Ground"
      url: "https://commonground.cg"
      role: "Co-Founder & Board Member"
    - name: "European Crypto Initiative"
      url: "https://eu.ci"
      role: "Co-Founder & Board Member"
  publications:
    - type: "Book"
      name: "Rechtshandbuch Legal Tech"
      publisher: "C.H.BECK"
      datePublished: "2021"
      role: "Co-Editor"
      edition: "2nd Edition"
    - type: "Book"
      name: "FinTech-Handbuch"
      publisher: "C.H.BECK"
      datePublished: "2024"
      role: "Contributing Author"
      edition: "3rd Edition"
    - type: "Periodical"
      name: "REthinking Law"
      publisher: "Handelsblatt Fachmedien"
      datePublished: "2018/2023"
      role: "Co-Editor & Co-Founder" 