title: Florian Glatz
description: Personal website of Florian Glatz, blockchain lawyer and researcher
baseurl: ""
url: ""

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - serve.sh 